model_params = Dict(
    :N_agents => 100,
    :N_attitude_dimensions => 2,
    :N_identity_dimensions => 2,
    :N_memorised_other => 50,
    :N_memorised_self => 25,
    :init_agent_attitude_overton_proportion => 0.5,
    :init_agent_attitude_std => 1.0,
    :N_search_points => 1,
    :inclusivity_scaler => 1.0,
    :attitude_shift_proportion => 0.2,
    :self_weight => 0.4, 
    :random_seed => 1234,
    :pull => 0.4,
    :sigmoid_slope_mod => 10.0,
    :sigmoid_slope_id => 10.0,
    :soft_overton_cost => 0.5,
    :hard_overton_cost => 0.5,
    :equal_dimprob_intervention => false,
    :cost_increment => 50.0,
    :intervention => :no_intervention,
    :intervention_time => 2_500_000,
    :cost_hike_intervention => false,
    :soft_hike_intervention => false,
    :window_change_intervention => false,
    :window_change => 0.0,
    :elite_anchor_intervention => false,
    :elite_anchor_strength => 1.0,
    :track_polarization => false,
    :only_esc => false
)
model_params[:dim_probs] = Float64[1.0 / model_params[:N_attitude_dimensions] for _ in 1:model_params[:N_attitude_dimensions]]
scaler = 5.0
model_params[:hard_overton_scalers] = [(scaler) for _ in 1:model_params[:N_attitude_dimensions]]
